# ==============================================================================
# run_all.R  —  master script: reproduce the entire analysis end-to-end.
# Usage:  Rscript R/run_all.R   (from the repo root, or anywhere)
# ==============================================================================
t0 <- Sys.time()
args <- commandArgs(FALSE)
fa <- grep("^--file=", args, value = TRUE)
script_dir <- if (length(fa)) dirname(normalizePath(sub("^--file=", "", fa[1]))) else file.path(getwd(), "R")
source(file.path(script_dir, "00_config.R"))          # sets CFG (incl. CFG$root)
source(file.path(CFG$root, "R", "plot_theme.R"))    # shared figure house style
steps <- c("01_prepare_data.R", "02_markov_model.R", "03_run_simulations.R",
           "04_dalys_costs_cea.R", "06_model_checks.R", "05_figures_tables.R", "07_sensitivity.R",
           "08_markov_diagram.R", "09_descriptive_addenda.R", "10_structural_scenarios.R",
           "11_additional_sensitivity.R")
for (s in steps) {
  message("\n=========== ", s, " ===========")
  source(file.path(CFG$root, "R", s))
}
# ---- Software provenance -----------------------------------------------------
# "R >= 4.5 with tidyverse" is not enough to reproduce a quantile or a figure.
# Record the exact environment, including the RNG kind, because the seed alone
# does not pin the stream. Written on every run so it cannot go stale.
prov <- file.path(CFG$dir_tab, "session_provenance.txt")
si <- utils::sessionInfo()
pkgs <- c(si$otherPkgs, si$loadedOnly)
writeLines(c(
  "# Software provenance for the epilepsy treatment-gap analysis",
  "# Regenerated by R/run_all.R on every run.",
  sprintf("r_version\t%s", si$R.version$version.string),
  sprintf("platform\t%s", si$platform),
  sprintf("running\t%s", si$running %||% NA_character_),
  sprintf("rng_kind\t%s", paste(RNGkind(), collapse = " / ")),
  sprintf("seed\t%d", CFG$seed),
  sprintf("psa_iterations\t%d", CFG$n_psa),
  "",
  "# package\tversion",
  sort(vapply(pkgs, function(p) sprintf("%s\t%s", p$Package, p$Version), ""))
), prov)
message("[run_all] wrote software provenance to ", prov)

message(sprintf("\n[run_all] DONE in %.1f s. Tables and figures in output/.",
                as.numeric(difftime(Sys.time(), t0, units = "secs"))))
